server.port=8080
spring.application.name=SBCParser
landingai.api.key=pat_yeAlwx3Ub86gPvFxkGK0lVAibj9qEL0i
landingai.api.url.parse=https://api.va.landing.ai/v1/ade/parse
landingai.api.url.extract=https://api.va.landing.ai/v1/ade/extract
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
